### ISSUE TITLE
q_networks.AC_net_keras, q_networks.q_network_keras and q_networks.q_network_theano only use 95mb of GPU

### ISSUE THREAD

**Issue by IanQS** [VinF/deer#47]
Do you happen to know a reason why it would use such little GPU memory? Trying to use the library but running into issues with this. It's saying that the GPU has no more space but the GPU has way more space than 95MB

**Comment by VinF** [comment]
It doesn't use much memory in the GPU because it loads a different mini-batch of tuples for every update from the replay memory (but there is indeed no reason that it explicitly says that the GPU has no more space).
Note that if you don't work with images (first four examples in the doc), you will probably be at the same speed (or even higher) with cpu only since the neural network would be quite simple.
